# Generated by Django 4.1.2 on 2022-12-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField(max_length=20)),
                ('company_link', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
